<?php

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form().
 *
 * We will only show the menu settings tab for the administrator and marketing_admin roles
 *
 */
function gsb_advanced_menu_customization_form_node_form_alter(&$form, &$form_state, $form_id) {

  global $user;

  // Hide the 'Menu Settings' tab for the node edit form if the user
  // doesn't have either the administrator, section manager or marketing_admin roles

  if (!in_array('section manager', $user->roles) && !in_array('marketing_admin', $user->roles) && !in_array('administrator', $user->roles)) {
    $form['menu']['#access'] = FALSE;
  }

}

